# Generated by Django 4.0.5 on 2022-07-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date', 'author'), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
